version: '3.1'

services:
  # test:
  #   build:
  #     context: .
  #     dockerfile: .roro/containers/web/Dockerfile
  #   # command: ["bin/rails", "s", "-b", "0.0.0.0"]
  #   command: ["bundle", "exec", "guard"]
  #   depends_on:
  #     - web
  #   env_file:
  #     - .roro/containers/web/test.env
  #     - .roro/containers/database/test.env
  #   stdin_open: true
  #   tty: true

  web:
    build:
      context: .
      dockerfile: .roro/containers/web/Dockerfile
    command: ["bin/rails", "s", "-b", "0.0.0.0"]
    depends_on:
      - database
    env_file:
      - .roro/containers/web/development.env
      - .roro/containers/database/development.env
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server
    ports:
      - "3000:3000"
      - "4000:4000"
    secrets:
      - host_ssh_key
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems

  webpack_dev_server:
    build:
      context: .
      dockerfile: .roro/containers/web/Dockerfile
    command: ["./bin/webpack-dev-server"]
    ports:
      - 3035:3035
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .roro/containers/web/development.env
      - .roro/containers/database/development.env
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  redis:
    image: redis

  database:
    image: postgres
    env_file:
      - .roro/containers/database/development.env
    volumes:
      - db_data:/var/lib/postgresql/data

  chrome:
    image: selenium/standalone-chrome-debug
    volumes:
      - /dev/shm:/dev/shm


volumes:
  db_data:
  gem_cache:

secrets:
  host_ssh_key:
    file: ~/.ssh/id_rsa
